// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: etcd.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Etcd message defines configuration information for etcd configuration center.
// Etcd is a distributed key-value store. This message is used to configure parameters required for interacting with etcd.
type Etcd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// endpoints is the list of etcd server endpoints.
	// Multiple endpoints can be specified for high availability.
	Endpoints []string `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// timeout is the timeout period for interacting with etcd services.
	// If no response is received within this time after sending a request, the request is considered timed out.
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// dial_timeout is the timeout for establishing connections to etcd.
	DialTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	// username is the username for etcd authentication.
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// password is the password for etcd authentication.
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// namespace is the namespace prefix for configuration keys.
	// All configuration keys will be prefixed with this namespace.
	Namespace string `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// enable_tls whether to enable TLS encryption.
	EnableTls bool `protobuf:"varint,7,opt,name=enable_tls,json=enableTls,proto3" json:"enable_tls,omitempty"`
	// cert_file is the path to the client certificate file.
	CertFile string `protobuf:"bytes,8,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	// key_file is the path to the client private key file.
	KeyFile string `protobuf:"bytes,9,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	// ca_file is the path to the CA certificate file.
	CaFile string `protobuf:"bytes,10,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	// enable_cache whether to enable local cache.
	// When enabled, configurations will be cached locally to reduce network requests.
	EnableCache bool `protobuf:"varint,11,opt,name=enable_cache,json=enableCache,proto3" json:"enable_cache,omitempty"`
	// enable_metrics whether to enable monitoring metrics.
	// When enabled, it will collect and report various monitoring metrics.
	EnableMetrics bool `protobuf:"varint,12,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"`
	// enable_retry whether to enable retry mechanism.
	// When enabled, it will automatically retry when connection fails.
	EnableRetry bool `protobuf:"varint,13,opt,name=enable_retry,json=enableRetry,proto3" json:"enable_retry,omitempty"`
	// max_retry_times maximum number of retries.
	MaxRetryTimes int32 `protobuf:"varint,14,opt,name=max_retry_times,json=maxRetryTimes,proto3" json:"max_retry_times,omitempty"`
	// retry_interval retry interval time.
	RetryInterval *durationpb.Duration `protobuf:"bytes,15,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`
	// enable_graceful_shutdown whether to enable graceful shutdown.
	// When enabled, it will gracefully close connections during shutdown.
	EnableGracefulShutdown bool `protobuf:"varint,16,opt,name=enable_graceful_shutdown,json=enableGracefulShutdown,proto3" json:"enable_graceful_shutdown,omitempty"`
	// shutdown_timeout graceful shutdown timeout.
	ShutdownTimeout *durationpb.Duration `protobuf:"bytes,17,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	// enable_logging whether to enable detailed logging.
	// When enabled, it will output detailed debug logs.
	EnableLogging bool `protobuf:"varint,18,opt,name=enable_logging,json=enableLogging,proto3" json:"enable_logging,omitempty"`
	// log_level log level.
	// Supported levels: debug, info, warn, error
	LogLevel string `protobuf:"bytes,19,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	// service_config configuration for remote service configuration loading
	ServiceConfig *ServiceConfig `protobuf:"bytes,20,opt,name=service_config,json=serviceConfig,proto3" json:"service_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Etcd) Reset() {
	*x = Etcd{}
	mi := &file_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etcd) ProtoMessage() {}

func (x *Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etcd.ProtoReflect.Descriptor instead.
func (*Etcd) Descriptor() ([]byte, []int) {
	return file_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *Etcd) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Etcd) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Etcd) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Etcd) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Etcd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Etcd) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Etcd) GetEnableTls() bool {
	if x != nil {
		return x.EnableTls
	}
	return false
}

func (x *Etcd) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Etcd) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *Etcd) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *Etcd) GetEnableCache() bool {
	if x != nil {
		return x.EnableCache
	}
	return false
}

func (x *Etcd) GetEnableMetrics() bool {
	if x != nil {
		return x.EnableMetrics
	}
	return false
}

func (x *Etcd) GetEnableRetry() bool {
	if x != nil {
		return x.EnableRetry
	}
	return false
}

func (x *Etcd) GetMaxRetryTimes() int32 {
	if x != nil {
		return x.MaxRetryTimes
	}
	return 0
}

func (x *Etcd) GetRetryInterval() *durationpb.Duration {
	if x != nil {
		return x.RetryInterval
	}
	return nil
}

func (x *Etcd) GetEnableGracefulShutdown() bool {
	if x != nil {
		return x.EnableGracefulShutdown
	}
	return false
}

func (x *Etcd) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

func (x *Etcd) GetEnableLogging() bool {
	if x != nil {
		return x.EnableLogging
	}
	return false
}

func (x *Etcd) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Etcd) GetServiceConfig() *ServiceConfig {
	if x != nil {
		return x.ServiceConfig
	}
	return nil
}

// ServiceConfig defines configuration for loading remote service configurations
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prefix is the configuration key prefix in etcd
	// If empty, uses the main etcd namespace
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// additional_prefixes defines additional prefixes to load
	// Each entry specifies a separate prefix to load
	AdditionalPrefixes []string `protobuf:"bytes,2,rep,name=additional_prefixes,json=additionalPrefixes,proto3" json:"additional_prefixes,omitempty"`
	// priority defines the merge priority (higher number = higher priority)
	// Default is 0, higher priority configs will override lower priority ones
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// merge_strategy defines how to handle conflicts with existing configs
	// "override" (default): later configs override earlier ones
	// "merge": merge nested objects, override leaf values
	// "append": append to arrays, override other values
	MergeStrategy string `protobuf:"bytes,4,opt,name=merge_strategy,json=mergeStrategy,proto3" json:"merge_strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ServiceConfig) GetAdditionalPrefixes() []string {
	if x != nil {
		return x.AdditionalPrefixes
	}
	return nil
}

func (x *ServiceConfig) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ServiceConfig) GetMergeStrategy() string {
	if x != nil {
		return x.MergeStrategy
	}
	return ""
}

var File_etcd_proto protoreflect.FileDescriptor

const file_etcd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"etcd.proto\x12\x19lynx.protobuf.plugin.etcd\x1a\x1egoogle/protobuf/duration.proto\"\xc9\x06\n" +
	"\x04Etcd\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12<\n" +
	"\fdial_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"enable_tls\x18\a \x01(\bR\tenableTls\x12\x1b\n" +
	"\tcert_file\x18\b \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\t \x01(\tR\akeyFile\x12\x17\n" +
	"\aca_file\x18\n" +
	" \x01(\tR\x06caFile\x12!\n" +
	"\fenable_cache\x18\v \x01(\bR\venableCache\x12%\n" +
	"\x0eenable_metrics\x18\f \x01(\bR\renableMetrics\x12!\n" +
	"\fenable_retry\x18\r \x01(\bR\venableRetry\x12&\n" +
	"\x0fmax_retry_times\x18\x0e \x01(\x05R\rmaxRetryTimes\x12@\n" +
	"\x0eretry_interval\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\rretryInterval\x128\n" +
	"\x18enable_graceful_shutdown\x18\x10 \x01(\bR\x16enableGracefulShutdown\x12D\n" +
	"\x10shutdown_timeout\x18\x11 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x12%\n" +
	"\x0eenable_logging\x18\x12 \x01(\bR\renableLogging\x12\x1b\n" +
	"\tlog_level\x18\x13 \x01(\tR\blogLevel\x12O\n" +
	"\x0eservice_config\x18\x14 \x01(\v2(.lynx.protobuf.plugin.etcd.ServiceConfigR\rserviceConfig\"\x9b\x01\n" +
	"\rServiceConfig\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12/\n" +
	"\x13additional_prefixes\x18\x02 \x03(\tR\x12additionalPrefixes\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12%\n" +
	"\x0emerge_strategy\x18\x04 \x01(\tR\rmergeStrategyB(Z&github.com/go-lynx/lynx-etcd/conf;confb\x06proto3"

var (
	file_etcd_proto_rawDescOnce sync.Once
	file_etcd_proto_rawDescData []byte
)

func file_etcd_proto_rawDescGZIP() []byte {
	file_etcd_proto_rawDescOnce.Do(func() {
		file_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_etcd_proto_rawDesc), len(file_etcd_proto_rawDesc)))
	})
	return file_etcd_proto_rawDescData
}

var file_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_etcd_proto_goTypes = []any{
	(*Etcd)(nil),                // 0: lynx.protobuf.plugin.etcd.Etcd
	(*ServiceConfig)(nil),       // 1: lynx.protobuf.plugin.etcd.ServiceConfig
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_etcd_proto_depIdxs = []int32{
	2, // 0: lynx.protobuf.plugin.etcd.Etcd.timeout:type_name -> google.protobuf.Duration
	2, // 1: lynx.protobuf.plugin.etcd.Etcd.dial_timeout:type_name -> google.protobuf.Duration
	2, // 2: lynx.protobuf.plugin.etcd.Etcd.retry_interval:type_name -> google.protobuf.Duration
	2, // 3: lynx.protobuf.plugin.etcd.Etcd.shutdown_timeout:type_name -> google.protobuf.Duration
	1, // 4: lynx.protobuf.plugin.etcd.Etcd.service_config:type_name -> lynx.protobuf.plugin.etcd.ServiceConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_etcd_proto_init() }
func file_etcd_proto_init() {
	if File_etcd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_etcd_proto_rawDesc), len(file_etcd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_etcd_proto_goTypes,
		DependencyIndexes: file_etcd_proto_depIdxs,
		MessageInfos:      file_etcd_proto_msgTypes,
	}.Build()
	File_etcd_proto = out.File
	file_etcd_proto_goTypes = nil
	file_etcd_proto_depIdxs = nil
}
